# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

COOKBOOK_PATH = ['./cookbooks', './vendor/cookbooks']
APP_IP = "172.16.33.11"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.define :proxy do |c|
    c.vm.network "private_network", ip: "192.168.33.10"
    c.vm.network "private_network", ip: "172.16.33.10", virtualbox__intnet: "infrataster-example"

    c.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = COOKBOOK_PATH
      chef.add_recipe "proxy"
      chef.json = {'app_ip' => APP_IP}
    end
  end

  config.vm.define :app do |c|
    c.vm.network "private_network", ip: APP_IP, virtualbox__intnet: "infrataster-example"

    c.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = COOKBOOK_PATH
      chef.add_recipe "app"
      chef.json = {}
    end
  end

  config.vm.define :db do |c|
    c.vm.network "private_network", ip: '172.16.33.12', virtualbox__intnet: "infrataster-example"

    c.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = COOKBOOK_PATH
      chef.add_recipe "db"
      chef.json = {'app_ip' => APP_IP}
    end
  end
end
