# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

COOKBOOK_PATH = ['./cookbooks', './vendor/cookbooks']
APP_IP = "172.16.33.11"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.define :proxy do |c|
    c.vm.network "private_network", ip: "192.168.33.10"
    c.vm.network "private_network", ip: "172.16.33.10", virtualbox__intnet: "infrataster-example"

    c.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = COOKBOOK_PATH
      chef.add_recipe "proxy"
      chef.json = {'app_ip' => APP_IP}
    end
  end

  config.vm.define :app do |c|
    c.vm.network "private_network", ip: APP_IP, virtualbox__intnet: "infrataster-example"

    c.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = COOKBOOK_PATH
      chef.add_recipe "app"
      chef.json = {}
    end
  end

  config.vm.define :db do |c|
    c.vm.network "private_network", ip: '172.16.33.12', virtualbox__intnet: "infrataster-example"

    c.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = COOKBOOK_PATH
      chef.add_recipe "db"
      chef.json = {'app_ip' => APP_IP}
    end
  end

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
  # config.vm.provision "chef_solo" do |chef|
  #   chef.cookbooks_path = "../my-recipes/cookbooks"
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
  #   chef.add_recipe "mysql"
  #   chef.add_role "web"
  #
  #   # You may also specify custom JSON attributes:
  #   chef.json = { :mysql_password => "foo" }
  # end

  # Enable provisioning with chef server, specifying the chef server URL,
  # and the path to the validation key (relative to this Vagrantfile).
  #
  # The Opscode Platform uses HTTPS. Substitute your organization for
  # ORGNAME in the URL and validation key.
  #
  # If you have your own Chef Server, use the appropriate URL, which may be
  # HTTP instead of HTTPS depending on your configuration. Also change the
  # validation key to validation.pem.
  #
  # config.vm.provision "chef_client" do |chef|
  #   chef.chef_server_url = "https://api.opscode.com/organizations/ORGNAME"
  #   chef.validation_key_path = "ORGNAME-validator.pem"
  # end
  #
  # If you're using the Opscode platform, your validator client is
  # ORGNAME-validator, replacing ORGNAME with your organization name.
  #
  # If you have your own Chef Server, the default validation client name is
  # chef-validator, unless you changed the configuration.
  #
  #   chef.validation_client_name = "ORGNAME-validator"
end
