# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
COOKBOOK_PATH = ['./cookbooks', './vendor/cookbooks']

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.define :proxy do |c|
    c.vm.network "private_network", ip: "192.168.44.10"
    c.vm.network "private_network", ip: "172.16.44.10", virtualbox__intnet: "infrataster-integration-test"

    c.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = COOKBOOK_PATH
      chef.add_recipe "apt-mirror"
      chef.json = {}
    end
  end

  config.vm.define :app do |c|
    c.vm.network "private_network", ip: '172.16.44.11', virtualbox__intnet: "infrataster-integration-test"

    c.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = COOKBOOK_PATH
      chef.add_recipe "apt-mirror"
      chef.json = {}
    end
  end
end
