# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant-itamae'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

INTERNAL_ADDRESSES = {
  'proxy' => '172.16.44.10',
  'app' => '172.16.44.11',
}

node_json = File.join(__dir__, 'node.json')
File.write(node_json, {'addresses' => INTERNAL_ADDRESSES}.to_json)

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define :proxy do |c|
    c.vm.network "private_network", ip: "192.168.44.10"
    c.vm.network "private_network", ip: INTERNAL_ADDRESSES['proxy'], virtualbox__intnet: "infrataster-integration-test"

    c.vm.provision :itamae do |c|
      c.sudo = true
      c.recipes = [File.join(__dir__, 'recipes/proxy/default.rb')]
      c.json = node_json
    end
  end

  config.vm.define :app do |c|
    c.vm.network "private_network", ip: INTERNAL_ADDRESSES['app'], virtualbox__intnet: "infrataster-integration-test"

    c.vm.provision :itamae do |c|
      c.sudo = true
      c.recipes = [File.join(__dir__, 'recipes/app/default.rb')]
      c.json = node_json
    end
  end
end
